// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHc7bRJ94CURMAOdlAagRJ9FSqpqOlzMg',
    appId: '1:401814859740:web:687c5eafbd82b735c8e919',
    messagingSenderId: '401814859740',
    projectId: 'iotsysenv-2b3f1',
    authDomain: 'iotsysenv-2b3f1.firebaseapp.com',
    storageBucket: 'iotsysenv-2b3f1.firebasestorage.app',
    measurementId: 'G-CXPJ1BT1N4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF-aKzaDRH4-eVa0MU-dcZc61IQUOn-rI',
    appId: '1:401814859740:android:9406bb8e41e7d2d5c8e919',
    messagingSenderId: '401814859740',
    projectId: 'iotsysenv-2b3f1',
    storageBucket: 'iotsysenv-2b3f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKHnpuzYCBrDiAOG_1jcAA4kJhv7KKM6c',
    appId: '1:401814859740:ios:1e6fa01962b7acdcc8e919',
    messagingSenderId: '401814859740',
    projectId: 'iotsysenv-2b3f1',
    storageBucket: 'iotsysenv-2b3f1.firebasestorage.app',
    iosBundleId: 'com.example.frontEndd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKHnpuzYCBrDiAOG_1jcAA4kJhv7KKM6c',
    appId: '1:401814859740:ios:1e6fa01962b7acdcc8e919',
    messagingSenderId: '401814859740',
    projectId: 'iotsysenv-2b3f1',
    storageBucket: 'iotsysenv-2b3f1.firebasestorage.app',
    iosBundleId: 'com.example.frontEndd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHc7bRJ94CURMAOdlAagRJ9FSqpqOlzMg',
    appId: '1:401814859740:web:a61b4e73cc55236ec8e919',
    messagingSenderId: '401814859740',
    projectId: 'iotsysenv-2b3f1',
    authDomain: 'iotsysenv-2b3f1.firebaseapp.com',
    storageBucket: 'iotsysenv-2b3f1.firebasestorage.app',
    measurementId: 'G-P2Z6PSZWTV',
  );
}
